# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
version-template: $MAJOR.$MINOR.$PATCH
# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: '✨ 新功能'
    labels:
      - '✨feat'
      - 'feat'
      - 'feature'
      - 'enhancement'
      - 'kind/feature'
  - title: '🔥 功能更新'
    labels:
      - '🔥update'
      - 'update'
  - title: '🐛 Bug修复'
    labels:
      - '🐛fix'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'regression'
      - 'kind/bug'
  - title: 📝 文档更新
    labels:
      - '📚docs'
      - 'doc'
      - 'docs'
      - documentation
      - 'kind/doc'
  - title: 💎 代码风格
    labels:
      - '💎style'
      - 'style'
      - 'styled'
      - 'styles'
  - title: 📦 代码重构
    labels:
      - '📦refactor'
      - 'refactor'
  - title: 🚀 性能提升
    labels:
      - '🚀perf'
      - 'pref'
  - title: 🚨 Test
    labels:
      - '🚨test'
      - 'test'
      - 'tests'
  - title: 🛠 系统构建、打包
    labels:
      - '🛠build'
      - 'build'
  - title: 🗑 代码恢复
    labels:
      - '🗑revert'
      - 'revert'
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid
change-template: '* $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## 更新内容

  $CHANGES
